spring.application.name=ApiGateway
server.port=8080

spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/user-service/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
eureka.instance.prefer-ip-address=true
#
## User Service Route
#spring.cloud.gateway.server.webflux.routes[0].id=user-service
#spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
#spring.cloud.gateway.server.webflux.routes[0].predicates[0].=Path=/user-service/**
#spring.cloud.gateway.server.webflux.routes[0].filters[0].=StripPrefix=1
#
## Account Service Route
#spring.cloud.gateway.server.webflux.routes[1].id=account-service
#spring.cloud.gateway.server.webflux.routes[1].uri=lb://account-service
#spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/account-service/**
#spring.cloud.gateway.server.webflux.routes[1].filters[0]=StripPrefix=1
#
## Notification Service Route
#spring.cloud.gateway.server.webflux.routes[2].id=notification-service
#spring.cloud.gateway.server.webflux.routes[2].uri=lb://NOTIFICATION-SERVICE
#spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/notification-service/**
#spring.cloud.gateway.server.webflux.routes[2].filters[0]=StripPrefix=1

